language: objective-c
osx_image: xcode8
script: 
 - xcodebuild test -project PSOperations.xcodeproj -scheme PSOperations -destination 'platform=iOS Simulator,name=iPhone 6s' -destination 'platform=tvOS Simulator,name=Apple TV 1080p'
 # - xcodebuild test -project PSOperations.xcodeproj -scheme PSOperationsAppForTests -destination 'platform=iOS Simulator,name=iPhone 6s'
